include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_positional_boolean_parameters
    - avoid_unused_constructor_parameters
    - directives_ordering
    - prefer_asserts_in_initializer_lists
    - prefer_if_elements_to_conditional_expressions
    - unawaited_futures
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unreachable_from_main
    - prefer_final_locals
    - prefer_const_constructors
    - omit_local_variable_types
